const mockHistory = [
     {
       name: "Dakota Fanning",
       rank: "TSgt",
       currentUnit: "55th OSS",
       projectedUnit: "97th IS",
       phoneNumber: "123-456-7892",
       email: "dakota.fanning@usaf.mil",
     },
     {
       name: "Brad Pitt",
       rank: "Capt",
       currentUnit: "338th CTS",
       projectedUnit: "343d RS",
       phoneNumber: "123-456-7893",
       email: "brad.pitt@usaf.mil",
     },
     {
       name: "Sherlock Holmes",
       rank: "2Lt",
       currentUnit: "338th CTS",
       projectedUnit: "55th OSS",
       phoneNumber: "123-456-7894",
       email: "sherlock.holmes@usaf.mil",
     },
     {
       name: "Marilyn Monroe",
       rank: "Amn",
       currentUnit: "97th IS",
       projectedUnit: "38th RS",
       phoneNumber: "123-456-7895",
       email: "marilyn.monroe@usaf.mil",
     },
     {
       name: "James Bond",
       rank: "MSgt",
       currentUnit: "38th RS",
       projectedUnit: "343d RS",
       phoneNumber: "123-456-7896",
       email: "james.bond@usaf.mil",
     },
     {
       name: "Harry Potter",
       rank: "SSgt",
       currentUnit: "97th IS",
       projectedUnit: "338th CTS",
       phoneNumber: "123-456-7897",
       email: "harry.potter@usaf.mil",
     },
     {
       name: "Lady Gaga",
       rank: "1Lt",
       currentUnit: "343d RS",
       projectedUnit: "97th IS",
       phoneNumber: "123-456-7898",
       email: "lady.gaga@usaf.mil",
     },
     {
       name: "Captain Jack Sparrow",
       rank: "Capt",
       currentUnit: "38th RS",
       projectedUnit: "55th OSS",
       phoneNumber: "123-456-7899",
       email: "jack.sparrow@usaf.mil",
     },
     {
       name: "Tony Stark",
       rank: "Maj",
       currentUnit: "480th ISR WG",
       projectedUnit: "9th RW",
       phoneNumber: "123-456-7900",
       email: "tony.stark@usaf.mil",
     },
     {
       name: "Natasha Romanoff",
       rank: "Col",
       currentUnit: "55th OSS",
       projectedUnit: "548th ISR Gp",
       phoneNumber: "123-456-7901",
       email: "natasha.romanoff@usaf.mil",
     },
   ];
   
export default mockHistory.js;
   