const rosterMockData = [
  {
    name: "Dakota Fanning",
    rank: "Captain",
    unit: "55th OSS",
    departureDate: "2023-07-12",
    arrivalDate: "2023-08-12",
    gainingUnit: "45th RS",
    losingUnit: "55th OSS",
    email: "dakota.fanning@hollywoodmail.com",
  },
  {
    name: "Brad Pitt",
    rank: "Lieutenant",
    unit: "338th CTS",
    departureDate: "2023-06-11",
    arrivalDate: "2023-08-11",
    gainingUnit: "97th IS",
    losingUnit: "338th CTS",
    email: "brad.pitstop@moviestar.net",
  },
  {
    name: "Sherlock Holmes",
    rank: "Major",
    unit: "338th CTS",
    departureDate: "2023-05-15",
    arrivalDate: "2023-08-15",
    gainingUnit: "343d RS",
    losingUnit: "338th CTS",
    email: "sherlock@bakerstreet.com",
  },
  {
    name: "Marilyn Monroe",
    rank: "Sergeant",
    unit: "97th IS",
    departureDate: "2023-04-10",
    arrivalDate: "2023-08-10",
    gainingUnit: "55th OSS",
    losingUnit: "97th IS",
    email: "marilyn@vintagemail.com",
  },
  {
    name: "James Bond",
    rank: "Commander",
    unit: "38th RS",
    departureDate: "2023-03-17",
    arrivalDate: "2023-08-17",
    gainingUnit: "338th CTS",
    losingUnit: "38th RS",
    email: "bond.jamesbond@mi6.uk",
  },
  {
    name: "Harry Potter",
    rank: "Second Lieutenant",
    unit: "97th IS",
    departureDate: "2023-02-18",
    arrivalDate: "2023-08-18",
    gainingUnit: "343d RS",
    losingUnit: "97th IS",
    email: "harry@hogwartsmail.com",
  },
  {
    name: "Lady Gaga",
    rank: "Colonel",
    unit: "343d RS",
    departureDate: "2023-01-14",
    arrivalDate: "2023-08-14",
    gainingUnit: "45th RS",
    losingUnit: "343d RS",
    email: "lady@gagamail.net",
  },
  {
    name: "Captain Jack Sparrow",
    rank: "Lieutenant Commander",
    unit: "38th RS",
    departureDate: "2022-12-10",
    arrivalDate: "2023-08-10",
    gainingUnit: "55th OSS",
    losingUnit: "38th RS",
    email: "captainjack@blackpearl.pirate",
  },
  {
    name: "Oprah Winfrey",
    rank: "Brigadier General",
    unit: "45th RS",
    departureDate: "2022-11-12",
    arrivalDate: "2023-08-12",
    gainingUnit: "97th IS",
    losingUnit: "45th RS",
    email: "oprah@talkshowqueen.com",
  },
  {
    name: "Tony Stark",
    rank: "General",
    unit: "38th RS",
    departureDate: "2022-10-16",
    arrivalDate: "2023-08-16",
    gainingUnit: "338th CTS",
    losingUnit: "38th RS",
    email: "tony@starkindustries.com",
  },
  {
    name: "Arya Stark",
    rank: "Private",
    unit: "338th CTS",
    departureDate: "2022-09-19",
    arrivalDate: "2023-08-19",
    gainingUnit: "55th OSS",
    losingUnit: "338th CTS",
    email: "arya@winterfell.net",
  },
  {
    name: "Emma Watson",
    rank: "Lieutenant Colonel",
    unit: "55th OSS",
    departureDate: "2023-08-05",
    arrivalDate: "2023-09-05",
    gainingUnit: "338th CTS",
    losingUnit: "55th OSS",
    email: "emma@hermionemail.com",
  },
  {
    name: "Morgan Freeman",
    rank: "Major General",
    unit: "45th RS",
    departureDate: "2023-07-25",
    arrivalDate: "2023-09-25",
    gainingUnit: "97th IS",
    losingUnit: "45th RS",
    email: "morgan@voiceofgod.com",
  },
  {
    name: "Scarlett Johansson",
    rank: "Captain",
    unit: "338th CTS",
    departureDate: "2023-06-20",
    arrivalDate: "2023-09-20",
    gainingUnit: "343d RS",
    losingUnit: "338th CTS",
    email: "scarlett@blackwidow.com",
  },
  {
    name: "Chris Evans",
    rank: "First Lieutenant",
    unit: "343d RS",
    departureDate: "2023-05-30",
    arrivalDate: "2023-09-30",
    gainingUnit: "38th RS",
    losingUnit: "343d RS",
    email: "chris@capmail.com",
  },
  {
    name: "Tom Hanks",
    rank: "Colonel",
    unit: "55th OSS",
    departureDate: "2023-04-15",
    arrivalDate: "2023-09-15",
    gainingUnit: "97th IS",
    losingUnit: "55th OSS",
    email: "tom@castawaymail.com",
  },
  {
    name: "Natalie Portman",
    rank: "Lieutenant",
    unit: "38th RS",
    departureDate: "2023-03-10",
    arrivalDate: "2023-09-10",
    gainingUnit: "343d RS",
    losingUnit: "38th RS",
    email: "natalie@queenamidala.com",
  },
  {
    name: "Leonardo DiCaprio",
    rank: "Major",
    unit: "97th IS",
    departureDate: "2023-02-22",
    arrivalDate: "2023-09-22",
    gainingUnit: "45th RS",
    losingUnit: "97th IS",
    email: "leo@titanicmail.com",
  },
  {
    name: "Jennifer Lawrence",
    rank: "Sergeant",
    unit: "343d RS",
    departureDate: "2023-01-18",
    arrivalDate: "2023-09-18",
    gainingUnit: "338th CTS",
    losingUnit: "343d RS",
    email: "jennifer@mockingjay.com",
  },
  {
    name: "Robert Downey Jr.",
    rank: "General",
    unit: "45th RS",
    departureDate: "2022-12-14",
    arrivalDate: "2023-09-14",
    gainingUnit: "38th RS",
    losingUnit: "45th RS",
    email: "robert@ironmanmail.com",
  },
  {
    name: "Gal Gadot",
    rank: "Captain",
    unit: "55th OSS",
    departureDate: "2022-11-20",
    arrivalDate: "2023-09-20",
    gainingUnit: "97th IS",
    losingUnit: "55th OSS",
    email: "gal@wonderwoman.com",
  },
  {
    name: "Matthew McConaughey",
    rank: "Lieutenant Colonel",
    unit: "338th CTS",
    departureDate: "2022-10-05",
    arrivalDate: "2023-09-05",
    gainingUnit: "343d RS",
    losingUnit: "338th CTS",
    email: "matthew@alrightmail.com",
  },
  {
    name: "Zendaya",
    rank: "First Lieutenant",
    unit: "97th IS",
    departureDate: "2022-09-29",
    arrivalDate: "2023-09-29",
    gainingUnit: "45th RS",
    losingUnit: "97th IS",
    email: "zendaya@euphoriamail.com",
  },
  {
    name: "Keanu Reeves",
    rank: "Major",
    unit: "38th RS",
    departureDate: "2022-08-19",
    arrivalDate: "2023-09-19",
    gainingUnit: "343d RS",
    losingUnit: "38th RS",
    email: "keanu@johnwick.com",
  },
  {
    name: "Emma Stone",
    rank: "Second Lieutenant",
    unit: "55th OSS",
    departureDate: "2022-07-12",
    arrivalDate: "2023-09-12",
    gainingUnit: "338th CTS",
    losingUnit: "55th OSS",
    email: "emma@lalaland.com",
  },
  {
    name: "Chris Hemsworth",
    rank: "Colonel",
    unit: "343d RS",
    departureDate: "2022-06-25",
    arrivalDate: "2023-09-25",
    gainingUnit: "97th IS",
    losingUnit: "343d RS",
    email: "chris@thormail.com",
  },
  {
    name: "Ryan Reynolds",
    rank: "Brigadier General",
    unit: "97th IS",
    departureDate: "2022-05-16",
    arrivalDate: "2023-09-16",
    gainingUnit: "45th RS",
    losingUnit: "97th IS",
    email: "ryan@deadpool.com",
  },
  {
    name: "Anne Hathaway",
    rank: "Sergeant",
    unit: "45th RS",
    departureDate: "2022-04-05",
    arrivalDate: "2023-09-05",
    gainingUnit: "338th CTS",
    losingUnit: "45th RS",
    email: "anne@princessdiary.com",
  },
  {
    name: "Hugh Jackman",
    rank: "General",
    unit: "55th OSS",
    departureDate: "2022-03-15",
    arrivalDate: "2023-09-15",
    gainingUnit: "38th RS",
    losingUnit: "55th OSS",
    email: "hugh@wolverine.com",
  },
  {
    name: "Dwayne Johnson",
    rank: "First Lieutenant",
    unit: "338th CTS",
    departureDate: "2022-02-25",
    arrivalDate: "2023-09-25",
    gainingUnit: "343d RS",
    losingUnit: "338th CTS",
    email: "dwayne@therock.com",
  },
  {
    name: "Mila Kunis",
    rank: "Captain",
    unit: "45th RS",
    departureDate: "2022-01-20",
    arrivalDate: "2023-09-20",
    gainingUnit: "97th IS",
    losingUnit: "45th RS",
    email: "mila@jupiterascend.com",
  },
];
 export default rosterMockData; 